stratosource/sfdiff/testfiles/rtest/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subregion__c</fullName>
        <label>Subregion</label>
        <picklist>
            <controllingField>Global_Region__c</controllingField>
            <picklistValues>
                <fullName>ASEAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fed Sled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Volume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mexico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDINO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEACA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northwest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soutwest</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

stratosource/sfdiff/testfiles/rtest/unpackaged/objects/SFDC_MDF__c.object
<CustomObject>
    <description>Captures a partner&apos;s request for funds defined in the budget for marketing development.</description>
    <fields>
        <fullName>Account_master__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fund Requests (Account Name)</relationshipLabel>
        <relationshipName>R00NR0000000QJRiMAO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Final Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending First Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Stage Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Stage Rejected</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Channel Budget</label>
        <referenceTo>SFDC_Budget__c</referenceTo>
        <relationshipName>R00NR0000000QJRyMAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel_Account_Manager__c</fullName>
        <label>Channel Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Fund_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel_Marketing_Manager_Country__c</fullName>
        <label>Channel Marketing Manager - Country</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Fund_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Red_Hat_Funding_Requested__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Estimated Red Hat Funding Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inside_Channel_Account_Manager__c</fullName>
        <label>Inside Channel Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Fund_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Program_Manager__c</fullName>
        <label>Marketing Program Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Fund_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oracle_Project_Code__c</fullName>
        <label>Oracle Project Code</label>
        <picklist>
            <picklistValues>
                <fullName>4608 - Trade Show / Event across Initiatives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4609 - Non-Initiative Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4617 - FreeToFee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4618 - UnixToLinux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4621 - Best Stack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4622 - RHEL In The Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4623 - RHEL Runs Best On RHEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4624 - CloudLead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4625 - JBoss Influence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4626 - JBoss Lead Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4627 - JBoss Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4629 - GLS Partner Training and Enablement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4630 - Field Partner Training and Enablement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Expenditure_of_Activity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Expenditure of Activity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Fund Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

stratosource/sfdiff/testfiles/rtest/unpackaged/classes/FundRequest_CancelTest.cls
@IsTest
private class FundRequest_CancelTest {
    public static FundRequest_Cancel instance {
        set;
        get;
    }
    
    public static void testConfirmUpdate(String globalRegion, String accountTeamMemberRole) {
        testConfirmUpdate(globalRegion, null, accountTeamMemberRole);
    }
       
    public static void testConfirmUpdate(String globalRegion, String subregion, String accountTeamMemberRole) {
        User user = [
             select Id
               from User
              where IsActive = true
              limit 1
        ];
        
        Account account = new Account();
        account.Name = 'Account';
        account.Global_Region__c = globalRegion;
        account.Subregion__c = subregion;
        insert account;
        
        AccountTeamMember accountTeamMember = new AccountTeamMember(AccountId = account.Id);
        accountTeamMember.UserId = user.Id;
        accountTeamMember.TeamMemberRole = accountTeamMemberRole;
        insert accountTeamMember;

        AccountShare accountShare = new AccountShare(AccountId = account.Id);
        accountShare.AccountAccessLevel = 'Edit';
        accountShare.OpportunityAccessLevel = 'None';
        accountShare.CaseAccessLevel = 'None';
        accountShare.UserOrGroupId = user.Id;
        insert accountShare;
        
        SFDC_Budget__c mdf = new SFDC_Budget__c();
        mdf.Name = 'Budget';
        mdf.Account_Master__c = account.Id;
        mdf.Active__c = true;
        mdf.Allocated_Budget__c = 100.00;
        mdf.Select_Fiscal_Year__c = 'Current Fiscal Year';
        mdf.Fiscal_Quarter__c = MDFTestSupport.getCurrentFiscalQuarter();
        mdf.Start_Date__c = MDFTestSupport.getCurrentStartDate();
        mdf.End_Date__c = MDFTestSupport.getCurrentEndDate();
        mdf.CurrencyIsoCode = 'USD';
        mdf.Channel_Account_Manager__c = user.Id;
        mdf.Channel_Marketing_Manager_Country__c = user.Id;
        mdf.Channel_Sales_Manager__c = user.Id;
        mdf.Marketing_Program_Manager__c = user.Id;
        mdf.Inside_Channel_Account_Manager__c = user.Id;
        insert mdf;
        
        SFDC_MDF__c fundRequest = new SFDC_MDF__c();
        fundRequest.Account_Master__c = mdf.Account_Master__c;
        fundRequest.Budget__c = mdf.Id;
        fundRequest.CurrencyIsoCode = 'USD';
        fundRequest.Total_Expenditure_of_Activity__c = 150.00;
        
    //Changes made by AM   
        
        fundRequest.Oracle_Project_Code__c = '4609 - Non-Initiative Program';
        
    //End of changes made by AM  
        
                
        fundRequest.Estimated_Red_Hat_Funding_Requested__c = 100.00;
        fundRequest.Approval_Status__c = 'Pending First Approval';
        fundRequest.Channel_Account_Manager__c = user.Id;
        fundRequest.Channel_Marketing_Manager_Country__c = user.Id;
        fundRequest.Marketing_Program_Manager__c = user.Id;
        fundRequest.Inside_Channel_Account_Manager__c = user.Id;
        insert fundRequest;

        fundRequest.Approval_Status__c = 'Approved';
        update fundRequest;

        instance = new FundRequest_Cancel(new ApexPages.StandardController(fundRequest));

        PageReference pageReference = instance.save();
        
        system.assertEquals(0, ApexPages.getMessages().size(), ApexPages.getMessages());
        system.assert(null != pageReference, 'Internal method must have failed.');
        
        system.assertEquals('Pending Cancellation', [
            select Approval_Status__c
              from SFDC_MDF__c
             where Id = :fundRequest.Id
        ].Approval_Status__c, 'Approval Status on Fund Request was not marked as Pending Cancellation.');
    }

    public static testmethod void testConfirmUpdate_NA() {
        testConfirmUpdate('NA', 'Channel Account Manager');
    }

    public static testmethod void testConfirmUpdate_NA_FedSled() {
        testConfirmUpdate('NA', 'Fed Sled', 'Marketing Program Manager');
    }

    public static testmethod void testConfirmUpdate_EMEA() {
        testConfirmUpdate('EMEA', 'Channel Marketing Manager - Country');
    }

    /* LATAM does not yet have an MDF cancellation process
     *
    public static testmethod void testConfirmUpdate_LATAM() {
        testConfirmUpdate('LATAM', 'Channel Account Manager');
    }
     */

    public static testmethod void testConfirmUpdate_APAC_GreaterChina() {
        testConfirmUpdate('APAC', 'Greater China', 'Channel Account Manager');
    }

    public static testmethod void testConfirmUpdate_APAC_Korea() {
        testConfirmUpdate('APAC', 'Korea', 'Channel Account Manager');
    }

    public static testmethod void testConfirmUpdate_APAC_Japan() {
        testConfirmUpdate('APAC', 'Japan', 'Channel Account Manager');
    }
}