stratosource/sfdiff/testfiles/rtest/unpackaged/objects/SFDC_MDF__c.object
<CustomObject>
    <description>Captures a partner&apos;s request for funds defined in the budget for marketing development.</description>
    <fields>
        <fullName>Account_master__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fund Requests (Account Name)</relationshipLabel>
        <relationshipName>R00NR0000000QJRiMAO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Approval_Status_Partner__c</fullName>
        <label>Approval Status: Partner</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Channel Budget</label>
        <referenceTo>SFDC_Budget__c</referenceTo>
        <relationshipName>R00NR0000000QJRyMAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Red_Hat_Funding_Requested__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Estimated Red Hat Funding Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Oracle_Project_Code__c</fullName>
        <label>Oracle Project Code</label>
        <picklist>
            <picklistValues>
                <fullName>4608 - Trade Show / Event across Initiatives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4609 - Non-Initiative Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4617 - FreeToFee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4618 - UnixToLinux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4621 - Best Stack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4622 - RHEL In The Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4623 - RHEL Runs Best On RHEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4624 - CloudLead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4625 - JBoss Influence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4626 - JBoss Lead Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4627 - JBoss Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4629 - GLS Partner Training and Enablement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4630 - Field Partner Training and Enablement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Expenditure_of_Activity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Expenditure of Activity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Fund Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

stratosource/sfdiff/testfiles/rtest/unpackaged/classes/FundRequest_CreateFundClaimTest.cls
@IsTest
private class FundRequest_CreateFundClaimTest {
    public static testmethod void testConstructor() {
        new FundRequest_CreateFundClaim(new ApexPages.StandardController(new SFDC_MDF__c()));
    }

    public static testmethod void testGetFundRequest() {
        Account account = new Account();
        account.Name = 'Account';
        insert account;
        
        SFDC_Budget__c mdf = new SFDC_Budget__c();
        mdf.Name = 'Budget';
        mdf.Account_Master__c = account.Id;
        mdf.Active__c = true;
        mdf.Allocated_Budget__c = 100.00;
        mdf.Select_Fiscal_Year__c = 'Current Fiscal Year';
        mdf.Fiscal_Quarter__c = MDFTestSupport.getCurrentFiscalQuarter();
        mdf.Start_Date__c = MDFTestSupport.getCurrentStartDate();
        mdf.End_Date__c = MDFTestSupport.getCurrentEndDate();
        mdf.CurrencyIsoCode = 'USD';
        insert mdf;

        SFDC_MDF__c fundRequest = new SFDC_MDF__c();        
        fundRequest.Account_Master__c = mdf.Account_Master__c;
        fundRequest.Budget__c = mdf.Id;
        fundRequest.CurrencyIsoCode = 'USD';
        fundRequest.Total_Expenditure_of_Activity__c = 100.00;
        fundRequest.Estimated_Red_Hat_Funding_Requested__c = 100.00;
        insert fundRequest;
        
        FundRequest_CreateFundClaim instance = new FundRequest_CreateFundClaim(new ApexPages.StandardController(fundRequest));
        system.assert(null != instance.fundRequest, 'FundRequest property on instance is null.');
        system.assertEquals(fundRequest.Id, instance.fundRequest.Id);
        system.assertEquals(fundRequest.Account_Master__c, instance.fundRequest.Account_Master__c);
    }

    public static testmethod void testConfirmUpdate() {
        Account account = new Account();
        account.Name = 'Account';
        insert account;
        
        SFDC_Budget__c mdf = new SFDC_Budget__c();
        mdf.Name = 'Budget';
        mdf.Account_Master__c = account.Id;
        mdf.Active__c = true;
        mdf.Allocated_Budget__c = 100.00;
        mdf.Select_Fiscal_Year__c = 'Current Fiscal Year';
        mdf.Fiscal_Quarter__c = MDFTestSupport.getCurrentFiscalQuarter();
        mdf.Start_Date__c = MDFTestSupport.getCurrentStartDate();
        mdf.End_Date__c = MDFTestSupport.getCurrentEndDate();
        mdf.CurrencyIsoCode = 'USD';
        insert mdf;

        SFDC_MDF__c fundRequest = new SFDC_MDF__c();        
        fundRequest.Account_Master__c = mdf.Account_Master__c;
        fundRequest.Budget__c = mdf.Id;
        fundRequest.CurrencyIsoCode = 'USD';
        
    //Changes made by AM   
        
        fundRequest.Oracle_Project_Code__c = '4609 - Non-Initiative Program';
        
    //End of changes made by AM  
        
        fundRequest.Total_Expenditure_of_Activity__c = 100.00;
        fundRequest.Estimated_Red_Hat_Funding_Requested__c = 100.00;
        fundRequest.Approval_Status_Partner__c = 'Approved'; // critical part
        insert fundRequest;
        
        system.assertEquals('Approved', [
            select Approval_Status_Partner__c
              from SFDC_MDF__c
             where Id = :fundRequest.Id
        ].Approval_Status_Partner__c, 'Approval_Status_Partner__c != Approved, as expected.');
        
        system.assert(null != new FundRequest_CreateFundClaim(new ApexPages.StandardController(fundRequest)).confirmUpdate());
    }

}